languageCode = "en-us"
title = "Rumproarious"
baseURL = "https://rumproarious.com/"
theme ="blank"
assetDir = "assets"
googleAnalytics = "UA-197961-20"
enableRobotsTXT = true # Suggested, enable robots.txt file

[permalinks]
  post = "/:year/:month/:day/:slug/"

[outputs]
home = [ "HTML", "jsonfeed", "RSS"]

[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true

[params]
  author = "Alex Kessinger"
  author_url = "https://twitter.com/voidfiles"
  google_fonts = [
    ["Libre Baskerville", "400, 700"],
    ["Open Sans", "400, 400i, 700, 700i"]
  ]

  heading_font = "Libre Baskerville"
  body_font = "Open Sans"

[markup.goldmark.renderer]
unsafe= true
