languageCode = "en-us"
title = "Rumproarious"
baseURL = "https://rumproarious.com/"
theme ="blank"
assetDir = "assets"
googleAnalytics = "UA-197961-20"
enableRobotsTXT = true # Suggested, enable robots.txt file

[permalinks]
  post = "/:year/:month/:day/:slug/"

[outputs]
home = [ "HTML", "jsonfeed", "RSS"]

[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true

[params]
  author = "Alex Kessinger"
  author_url = "https://twitter.com/voidfiles"

[markup.goldmark.renderer]
unsafe= true